language: python

# Supported Python versions
python:
  - "3.5"
  - "3.6"

services:
  - postgresql

before_script:
  - psql -c 'create database ah_jumanji;' -U postgres

# Define env variables
env:
  - DJANGO_SETTINGS_MODULE="authors.settings"

# Install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest

# Run tests
script:
  - pytest
  - pytest --cov=authors/

# Generate coverage report
after_success:
  - coveralls

notifications:

  slack: andela:TZIVZCX4fSQf9zrBJjXD8Eq7

cache: pip
